name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  merge_group:
jobs:
  test:
    name: Test ${{ matrix.os }} - ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11"]

    steps:
      # Checkout either the PR or the branch
      - name: Checkout PR
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "${{matrix.python-version}}"
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml

      - uses: extractions/setup-just@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          just venv

      - name: Run tests
        run: just test

  passed:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: |
          echo Tests passed
